[project]
name = "ai-me-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "optuna>=4.5.0",
    "pycaret>=3.3.2",
    "seaborn>=0.13.2",
    "xgboost>=3.0.5",
]
